version: "3.9"

services:
  django-server:
    build: ./TEQServer
    container_name: django-server
    ports:
      - "8000:8000"
    env_file:
      - ./TEQServer/.env
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - backend

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - backend

  celery:
    build: ./TEQServer
    container_name: celery_worker
    command: celery -A teqserver worker --loglevel=info
    env_file:
      - ./TEQServer/.env
    depends_on:
      - redis
      - django-server
    networks:
      - backend

  vue-frontend:
    build: ./TEQClient/teqclient
    container_name: vue-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - django-server
    networks:
      - backend

volumes:
  postgres_data:
  mongo_data:

networks:
  backend:
    driver: bridge