# Generated by Django 5.1.3 on 2025-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_test_version_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='max_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='auto_check',
            field=models.BooleanField(default=False),
        ),
    ]
