# Generated by Django 5.1.3 on 2025-04-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_show_result_answer_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='show_correct',
            field=models.BooleanField(default=False),
        ),
    ]
