# Generated by Django 5.1.3 on 2025-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_test_show_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='show_correct',
            field=models.BooleanField(default=False),
        ),
    ]
