# Generated by Django 5.1.3 on 2025-04-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_answer_show_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='grade',
        ),
    ]
