# Generated by Django 5.1.3 on 2025-04-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_test_can_share_testpool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPool',
        ),
    ]
