# Generated by Django 5.1.3 on 2025-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_testpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
